/*	PROGRAM TO CREATE A FILE SO THAT IT CAN BE ACCESSESD ONLY IF YOU HAVE THE PASSWORD
	1. TO RECORD A NEW MESSAGE OPEN THE SOURCE FILE IN TEXT EDITOR
	2. ADD THE MESSAGE IN AN ARRAY OF 1000
	3. SET THE PASSWORD THROUGH THE EDITOR
	4. COMPILE THE C FILE 
	5. SEND THE EXE FILE TO THE OTHER PERSON
	6. AND HOPE THAT HE OPENS IT UP
	*/
	
#include<stdio.h>
#include<conio.h>
#include<string.h>
#include"DISPLAY.h"

#include"EXIT_MESSAGE.c"
#include"MESSAGE.c"
#include"INTRO.c"
#include"PROGRAM.c"

void main(void){
	system("color 0A");
	PROGRAM();
}
